services:

  # MongoDB service
  mongo-db:
    container_name: mongo-db-internet-shop
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mongo_internet_shop
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  mongo_data: